### ISSUE TITLE
Create3 is not time synced.

### ISSUE THREAD

**Issue by ChristianWieck** [turtlebot/turtlebot4#404]
### Robot Model

Turtlebot 4 - Standard

### ROS distro

Humble

### Networking Configuration

Discovery Server

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

Does not apply.

### Type of issue

Other

### Expected behaviour

The Create3 syncs it's time with the raspi when the `ntp.conf` is set to
```
# Use RPi4 as preferred server
# Minpoll 2^4 = 16s
# Maxpoll 2^6 = 64s
server 192.168.186.3 prefer iburst minpoll 4 maxpoll 6
```

### Actual behaviour

The Create3 does not sync it's time. Instead the raspi is rejected as the delay is too big
```
Apr 26 11:31:06 iRobot-A06C5E984CFD42A4A5D811888A8F9AE7 user.notice ntpd: ntpd: reply from 192.168.186.3: delay 0.004586 is too high, ignoring
```

This leads to an unusable Nav2 stack as the tfs (especially the `odom` from the create3) is not synced.

### Error messages

```bash
See attached log in first comment.
```

### To Reproduce

1. Start the Turtlebot4.
2. Check that the raspi is synced (`chronyc tracking` gives a sub millisecond error)
3. Look at the Create3 log

**Comment by ChristianWieck** [comment]
The log of the create3 platform.
[Create3.log](https://github.com/turtlebot/turtlebot4/files/15130085/Create3.log)

**Comment by smatarCPR** [comment]
Hello @ChristianWieck ,
Thank you for reaching out on the Turtlebot 4 Github page. After making the changes to the ntp.comf file, did you restart the service using the Beta Features -> Restart ntpd?

The ntp server attempts to adjust time at small increments to prevent clock issues on the system, does delay change value if you wait a some time?

Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by ChristianWieck** [comment]
Thanks for coming back. I restarted the ntp server und power cycled the complete robot.

Waiting did not solve the problem - the robot was running for a good twenty minutes or so. Also the log messages indicate that the create 3 platform is not accepting the ntp updates from the pi as there latency is to high (at least that's my interpretation).

If you need any further logs or dumps let me know.

**Comment by smatarCPR** [comment]
Hello @ChristianWieck ,
What version of firmware is being used on the Create3? In older revisions of the firmware, the CPU usage was quite high. This resulted in the occasionally, the Create3 failing to sync due to high CPU usage. This issue has been addressed in the latest firmware version. H.2.6.

Download the latest firmware file for Humble from this link - https://iroboteducation.github.io/create3_docs/releases/overview/

Upload the update file per the instructions found here - https://iroboteducation.github.io/create3_docs/webserver/update/

Let me know how this recommendation works for, or if you are already running firmware version H.2.6.

Looking forward to hearing from you soon.
Best Regards,
Saif

**Comment by ChristianWieck** [comment]
Hello,

In fact, we were already running the H.2.6 firmware on the Create3 when the issue was opened.
![Screenshot from 2024-05-07 07-59-16](https://github.com/turtlebot/turtlebot4/assets/167854903/c038d893-72f0-4fb2-af87-373fcb894e06)

While this helped with the general responsiveness of the TB, it did not solve the sync problem.

**Comment by smatarCPR** [comment]
Hello @ChristianWieck ,
Thank you for providing this update. Reviewing the log files you have sent, it appears that occasionally, the Create3 is able to sync with the Raspberry Pi
```
Apr 26 11:29:29 iRobot-A06C5E984CFD42A4A5D811888A8F9AE7 user.notice ntpd: ntpd: setting time to 2024-04-26 11:29:29.710608 (offset +62.230608s)
Apr 26 11:29:29 iRobot-A06C5E984CFD42A4A5D811888A8F9AE7 kern.notice kernel: [   42.310018] random: bluetoothd: uninitialized urandom read (4 bytes read)
Apr 26 11:29:29 iRobot-A06C5E984CFD42A4A5D811888A8F9AE7 user.notice ntpd: Time has been adjusted
``` 

Beyond the millisecond difference you mentioned seeing in Chrony, are you able to otherwise use the Turtlebot 4? Have you noticed any issues when trying to run certain toolsets (such as the Nav demo)?

Are you able to visualise the robot in RVIZ?

If the option is available to you, try factory resetting the TB4 by [reflashing the SD card](https://turtlebot.github.io/turtlebot4-user-manual/setup/basic.html#install-latest-raspberry-pi-image) and [factory resetting the Create3](https://iroboteducation.github.io/create3_docs/webserver/about/#:~:text=set%20to%20USB.-,Factory%20Reset,-A%20hyperlink%20to).

Let me know how this recommendation works for you. Looking forward to hearing from you soon.
Best Regards,
Saif M.

**Comment by ChristianWieck** [comment]
Hi,

Thanks for the reply. The log message does indeed indicate that the time synchronization is happening.

We can use the TB, but the Nav2 demo (and the Nav2 stack itself) doesn't work. The - paraphrased - log message is that the Odom frame is out of sync with the rest of the robot - hence my suspicion that the time sync didn't work.
Rviz does load the global map but fails to localize the robot in it. It's simply located at the maps origin. AMCL complains that the `odom` transform is too old to be used and extrapolation would be required.
Unfortunately, I won't be able to provide detailed logs for another week and a half as I am away from the robot.

**Comment by smatarCPR** [comment]
Hello,
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
Best Regards,
Saif

**Comment by swapchal** [comment]
Hi, were you able to solve this issue?

**Comment by ChristianWieck** [comment]
Hey, unfortunately we were not. We ended up switching to a different type of robot that did not have these issues. However, there was a relatively large update to the TB stack a few days/weeks ago. Maybe that fixed the problem?

**Comment by swapchal** [comment]
Out of curiosity, what’s the new robot?

**Comment by ChristianWieck** [comment]
We still had a Clearpath Jackal standing around which worked fine but is a different price point.

**Comment by FGJoseMiguel-AIST** [comment]
I have the same problem, the create3 doesn't want to fully sincronize and it's around 5 seconds in the future making imposible to use the nav stack
